### ISSUE TITLE
Position:fixed hatasi 

### ISSUE THREAD

**Issue by berkaybeyaz1** [baransomakli/softgrid#5]
``` html
    <div class="row">
        <div class="two colon"> left bar</div>
        <div class="nine colon"> right bar</div>
    </div>
```

boyle bir yapim var left bar a `position:fixed` verince asagidaki resim gibi oluyor.
![error](https://cloud.githubusercontent.com/assets/7584428/15453951/771ac2b2-2032-11e6-8a55-675c1fd73e03.PNG)

**Comment by btk** [comment]
2'nci .colon divi için float:right; verirsen sorun çözülecektir. Ayrıca kodun kendisinde de şöyle bir düzenleme yaptım, yeni versiyon ile kullanabilirsin.

https://github.com/baransomakli/softgrid/pull/6

**Comment by berkaybeyaz1** [comment]
Sagolun tesekkurler kapatabilirsiniz issueyi :)

**Comment by baransomakli** [comment]
Teşekkürler Burak abi.
